language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - jruby-9.1.17.0
  - rbx-3.105
  - ruby-head
jdk:
  - openjdk8 # for jruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3.105
before_install:
  - gem install bundler
notifications:
  irc: "irc.freenode.org#adhearsion"
